# Generated by Django 4.1.5 on 2023-01-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whereis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat_lon',
            field=models.CharField(default='51.01454,11.04377', max_length=200),
        ),
    ]
